### ISSUE TITLE
Buffer insufficient error when decoding WEBP image.

### ISSUE THREAD

**Issue by shravan2x** [saucecontrol/PhotoSauce#167]
The issue occurs only when the `Width` and `Height` settings are used. It succeeds otherwise.
Libwebp works correctly, but Windows default codecs fail.

Repro:
```c#
byte[] fileBytes = File.ReadAllBytes("photo-1517022812141-23620dba5c23.webp");

using MemoryStream processedImageMemoryStream = new MemoryStream();
ProcessImageSettings processImageSettings = new ProcessImageSettings()
{
    Width = 1500,
    Height = 0,
    ResizeMode = CropScaleMode.Max,
    Interpolation = InterpolationSettings.Lanczos,
    EncoderOptions = new JpegEncoderOptions() { Quality = 95, SuppressApp0 = true }
};
MagicImageProcessor.ProcessImage(fileBytes, processedImageMemoryStream, processImageSettings);
```

Image that causes the issue (zipped as github didn't allow uploading .webp files directly) [photo-1517022812141-23620dba5c23.zip](https://github.com/user-attachments/files/17237168/photo-1517022812141-23620dba5c23.zip)

Stack trace:
```
System.Runtime.InteropServices.COMException (0x88982F8C): The buffer allocated is insufficient. (0x88982F8C)
   at PhotoSauce.MagicScaler.WicFramePixelSource.CopyPixelsInternal(PixelArea& prc, Int32 cbStride, Int32 cbBufferSize, Byte* pbBuffer)
   at PhotoSauce.MagicScaler.Transforms.ConversionTransform.copyPixelsDirect(PixelArea& prc, Int32 cbStride, Byte* pbBuffer)
   at PhotoSauce.MagicScaler.PixelSource.CopyPixels(PixelArea& prc, Int32 cbStride, Int32 cbBufferSize, Byte* pbBuffer)
   at PhotoSauce.MagicScaler.Transforms.ConvolutionTransform`3.CopyPixelsInternal(PixelArea& prc, Int32 cbStride, Int32 cbBufferSize, Byte* pbBuffer)
   at PhotoSauce.MagicScaler.Transforms.ConvolutionTransform`3.CopyPixelsInternal(PixelArea& prc, Int32 cbStride, Int32 cbBufferSize, Byte* pbBuffer)
   at PhotoSauce.MagicScaler.Transforms.ConversionTransform.copyPixelsBuffered(PixelArea& prc, Int32 cbStride, Byte* pbBuffer)
   at PhotoSauce.MagicScaler.PixelSource.CopyPixels(PixelArea& prc, Int32 cbStride, Int32 cbBufferSize, Byte* pbBuffer)
   at PhotoSauce.Interop.Wic.IWICBitmapSourceImpl.copyPixels(IWICBitmapSource* pinst, WICRect* prc, UInt32 cbStride, UInt32 cbBufferSize, Byte* pbBuffer)
   at PhotoSauce.MagicScaler.WicImageEncoder.writeSource(IWICBitmapFrameEncode* frame, PixelSource src, PixelArea area)
   at PhotoSauce.MagicScaler.WicImageEncoder.WriteFrame(IPixelSource source, IMetadataSource meta, Rectangle area)
   at PhotoSauce.MagicScaler.MagicImageProcessor.WriteOutput(PipelineContext ctx, Stream ostm)
   at PhotoSauce.MagicScaler.MagicImageProcessor.ProcessImage(ReadOnlySpan`1 imgBuffer, Stream outStream, ProcessImageSettings settings)
```

**Comment by saucecontrol** [comment]
Thanks for the report.  I see the same when using the WIC codecs.  Worth noting it does not repro when using the [libwebp plugin](https://www.nuget.org/packages/PhotoSauce.NativeCodecs.Libwebp/1.3.2-preview3).

**Comment by saucecontrol** [comment]
Turned out this was just some bogus validation in the WIC codec.  It errors if the pixel buffer's stride is larger than the buffer itself.  Fixed in https://github.com/saucecontrol/PhotoSauce/commit/47ddfd62979a3c40c3883cf5adb3457f03176f02

Thanks again for the report!

**Comment by saucecontrol** [comment]
New release is up.
