### ISSUE TITLE
Random NullReferenceException when processing bitonal (black/white) images

### ISSUE THREAD

**Issue by ra-magnus-welander** [saucecontrol/PhotoSauce#69]
This exception occurs randomly (but frequently enough) when we try to convert bitonal images. The caller is our own .NET implementation of a IIIF-server which serves image tiles to a client which often requests several tiles simultaneously. Sometimes, randomly, a tile will not load. I have not been able to reproduce the bug with a single call.

All other images we have tried work flawlessly. Only bitonal images are affected.

This affects v 0.12.0. We have also tested v 0.11.2 where bitonal images work.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at PhotoSauce.Interop.Wic.IWICBitmapSourceImpl.CopyPixels(IWICBitmapSourceImpl* pinst, WICRect* prc, UInt32 cbStride, UInt32 cbBufferSize, Byte* pbBuffer)
   at TerraFX.Interop.IWICBitmapSource.CopyPixels(WICRect* prc, UInt32 cbStride, UInt32 cbBufferSize, Byte* pbBuffer)
   at PhotoSauce.MagicScaler.WicPixelSource.CopyPixelsInternal(PixelArea& prc, Int32 cbStride, Int32 cbBufferSize, IntPtr pbBuffer)
   at PhotoSauce.MagicScaler.PixelSource.CopyPixels(PixelArea& prc, Int32 cbStride, Int32 cbBufferSize, IntPtr pbBuffer)
   at PhotoSauce.MagicScaler.Transforms.HybridScaleTransform.CopyPixelsInternal(PixelArea& prc, Int32 cbStride, Int32 cbBufferSize, IntPtr pbBuffer)
   at PhotoSauce.MagicScaler.PixelSource.CopyPixels(PixelArea& prc, Int32 cbStride, Int32 cbBufferSize, IntPtr pbBuffer)
   at PhotoSauce.MagicScaler.Transforms.ConvolutionTransform`2.loadBuffer(Int32 first, Int32 lines)
   at PhotoSauce.MagicScaler.Transforms.ConvolutionTransform`2.CopyPixelsInternal(PixelArea& prc, Int32 cbStride, Int32 cbBufferSize, IntPtr pbBuffer)
   at PhotoSauce.MagicScaler.PixelSource.CopyPixels(PixelArea& prc, Int32 cbStride, Int32 cbBufferSize, IntPtr pbBuffer)
   at PhotoSauce.Interop.Wic.IWICBitmapSourceImpl.CopyPixels(IWICBitmapSourceImpl* pinst, WICRect* prc, UInt32 cbStride, UInt32 cbBufferSize, Byte* pbBuffer)
   at TerraFX.Interop.IWICBitmapFrameEncode.WriteSource(IWICBitmapSource* pIBitmapSource, WICRect* prc)
   at PhotoSauce.MagicScaler.WicImageEncoderFrame.WriteSource(PipelineContext ctx, PixelArea area)
   at PhotoSauce.MagicScaler.MagicImageProcessor.WriteOutput(PipelineContext ctx, Stream ostm)
   at PhotoSauce.MagicScaler.MagicImageProcessor.ProcessImage(Stream imgStream, Stream outStream, ProcessImageSettings settings)
```

**Comment by ra-magnus-welander** [comment]
Example image
![00000001](https://user-images.githubusercontent.com/14177560/116541805-34695a80-a8ec-11eb-891e-2bbedbbd5f34.png)

**Comment by saucecontrol** [comment]
Hey Magnus, thanks for the report.  From your stack trace, it looks like a managed `PixelSource` owned only by a WIC wrapper has been garbage collected while still in use.  That would explain the random nature of the issue since it would depend on GC running during processing of an affected image.  The WIC wrappers hold only a weak GC reference in order to prevent a reference cycle that would prevent collection when a pipeline is not properly disposed by a client and relies on finalizers to clean up.

The assumption there is that the pipeline itself will hold a strong reference to the managed component as well, but I think you've found a case where a native-to-managed wrapper references a managed-to-native wrapper that performs the required 1-bit to 8-bit conversion.

I wasn't entirely happy with the design of that when I put it together, so I've recently overhauled the PixelSource ownership model to make the ownership between pipeline components more explicit.  If you're able to try out the latest [CI build](https://dev.azure.com/saucecontrol/PhotoSauce/_packaging?_a=feed&feed=photosauce_ci), the problem might already be solved.  Otherwise, I think I understand enough about what might be happening that I can create a test to repro it more reliably, so I'll do some testing on my end.

**Comment by ra-magnus-welander** [comment]
Thank you very much for the quick reply, Clinton!

I have tried the CI build and indeed it seems to have resolved this problem. At least I haven't been able to reproduce it again. So, problem solved, I guess 😎

**Comment by saucecontrol** [comment]
Thanks for the quick feedback on that. I tried to repro the issue over here running with GCStress and couldn't get it to happen even with that.  I'll take your word it's resolved 😄 

I've just pushed a new release with the changes.

**Comment by ra-magnus-welander** [comment]
Great work, thanks!
